// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQtzvt8JIGF4u-SVpjZbVdVZY2xp9iYGg',
    appId: '1:14033129859:web:dfd2168ea2af510c8326b6',
    messagingSenderId: '14033129859',
    projectId: 'project01-146f2',
    authDomain: 'project01-146f2.firebaseapp.com',
    storageBucket: 'project01-146f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9tYjTUzdGHna8Rhf22UbWe25Z_M54MjI',
    appId: '1:14033129859:android:7b724c4362bb2a8c8326b6',
    messagingSenderId: '14033129859',
    projectId: 'project01-146f2',
    storageBucket: 'project01-146f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPqWWPpaXx8z7klrts6yRJoid2R6lHM_g',
    appId: '1:14033129859:ios:4ed8ef6cc4bde1748326b6',
    messagingSenderId: '14033129859',
    projectId: 'project01-146f2',
    storageBucket: 'project01-146f2.appspot.com',
    iosBundleId: 'com.example.project02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPqWWPpaXx8z7klrts6yRJoid2R6lHM_g',
    appId: '1:14033129859:ios:ea460748616a08e48326b6',
    messagingSenderId: '14033129859',
    projectId: 'project01-146f2',
    storageBucket: 'project01-146f2.appspot.com',
    iosBundleId: 'com.example.project02.RunnerTests',
  );
}
